webtalk_init -webtalk_dir /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/project_1.sim/sim_1/behav/xsim/xsim.dir/MCP_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 22 19:40:45 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3da3bc14-bd35-417b-b8f0-72c2dcd793d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e6209bc10f2547bf9e738d43b718f40c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "156" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "n/a" -context "user_environment"
webtalk_add_data -client project -key os_release -value "NAME="Red Hat Enterprise Linux Server"" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7542 32-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "80 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "155120_KB" -context "xsim\\usage"
webtalk_transmit -clientid 732995444 -regid "" -xml /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/project_1.sim/sim_1/behav/xsim/xsim.dir/MCP_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/project_1.sim/sim_1/behav/xsim/xsim.dir/MCP_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/project_1.sim/sim_1/behav/xsim/xsim.dir/MCP_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
