#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 22 19:12:15 IST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim MCP_tb_behav -key {Behavioral:sim_1:Functional:MCP_tb} -tclbatch MCP_tb.tcl -view /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/MCP_tb_behav.wcfg -log simulate.log"
xsim MCP_tb_behav -key {Behavioral:sim_1:Functional:MCP_tb} -tclbatch MCP_tb.tcl -view /home/24CAP1G13/Desktop/MCP/Assignment_1_MCP/MCP_tb_behav.wcfg -log simulate.log

